version: '3.8'

services:
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./auth/.env
    restart: unless-stopped

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - ./user/.env
    restart: unless-stopped

  tutor-service:
    build:
      context: ./tutor
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    env_file:
      - ./tutor/.env
    restart: unless-stopped
