DROP TABLE IF EXISTS payouts CASCADE;
DROP TABLE IF EXISTS wallet_entries CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS commissions CASCADE;
DROP TABLE IF EXISTS payments CASCADE;